pipeline {
    agent any
    options {
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Select The Environment')
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Create or Destroy')
    }

    stages {
        stage('terraform init') {
            steps { 
                    // below is the groovy script to clone the reppo and you need to enclose them with the {}
                   script { git branch: 'main', url: 'https://github.com/santhosh-patchigolla/cart.git' }
                    sh "ls -ltr"
                    sh "pwd"
                    sh "cd mutable-infra"
                    sh "terrafile -f env-${ENV}/Terrafile"
                    sh "terraform init -backend-config=env-${ENV}/${ENV}-backend.tfvars"
            }
        }

        stage('terraform plan') {
            steps { 
                    sh "cd mutable-infra"
                    sh "terraform plan -var-file=env-${ENV}/${ENV}.tfvars"
            }
        }

        stage('terraform apply') {
            steps { 
                    sh "cd mutable-infra"
                    sh "terraform ${ACTION} -auto-approve -var-file=env-${ENV}/${ENV}.tfvars"
            }
        }
    }
 }



// @Library('roboshop-shared-library') _

// env.REPONAME="cart"
// env.TFDIR="mutable-infra"
// backendInfra()
